#!/usr/bin/env python
# -*- coding: cp1251 -*-



##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from admin_main import admin_main

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0rc8'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 8)
__CHEETAH_genTime__ = 1482336166.148
__CHEETAH_genTimestamp__ = 'Wed Dec 21 18:02:46 2016'
__CHEETAH_src__ = 'systems\\ENGINE\\ADMINPANEL\\templates\\admin_send_msg.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Dec 21 09:10:12 2016'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class admin_send_msg(admin_main):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        admin_main.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def adminData(self, **KWS):



        ## CHEETAH: generated from #def adminData at line 3, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''
<h3>\xce\xf2\xef\xf0\xe0\xe2\xea\xe0 \xf1\xee\xee\xe1\xf9\xe5\xed\xe8\xe9</h3>
<div>
  <div border=1 class="container" style="position:relative; float:left">
    <form name="send_msg_form" id="send_msg_form">
      <fieldset>
        <legend align="center"><h5>\xcf\xe0\xf0\xe0\xec\xe5\xf2\xf0\xfb</h5></legend>
        <br/>
          <p>
          <label style="display: -moz-inline-box;" for="systems_cmb"><span style="display: block; width: 200px;">\xd1\xe8\xf1\xf2\xe5\xec\xe0-\xef\xee\xeb\xf3\xf7\xe0\xf2\xe5\xeb\xfc</span></label>
          <select id="systems_cmb" name="systems_cmb" style="width: 400px">
          <optgroup label="\xc2\xfb\xe1\xe5\xf0\xe8\xf2\xe5 \xf1\xe8\xf1\xf2\xe5\xec\xf3...">
              <option value="--ALL--SYSTEMS--">\xc2\xd1\xc5 \xd1\xc8\xd1\xd2\xc5\xcc\xdb</option>
''')
        for system in VFFSL(SL,"datalist_systems",True): # generated from line 17, col 15
            write('''                  <option value="''')
            _v = VFFSL(SL,"system.ID_SYSTEM",True) # '$system.ID_SYSTEM' on line 18, col 34
            if _v is not None: write(_filter(_v, rawExpr='$system.ID_SYSTEM')) # from line 18, col 34.
            write('''">''')
            _v = VFFSL(SL,"system.spaces",True) # '${system.spaces}' on line 18, col 53
            if _v is not None: write(_filter(_v, rawExpr='${system.spaces}')) # from line 18, col 53.
            _v = VFFSL(SL,"system.SHOW_NAME",True) # '$system.SHOW_NAME' on line 18, col 69
            if _v is not None: write(_filter(_v, rawExpr='$system.SHOW_NAME')) # from line 18, col 69.
            write('''</option>
''')
        write('''          </optgroup>
          </select>
          </p>

          <br/>

          <p align="left">
          <label style="display: -moz-inline-box;" for="expired_time_edt"><span style="display: block; width: 200px; text-align: center">\xd1\xeb\xe0\xf2\xfc \xef\xee (\xe2\xf0\xe5\xec\xff)</span></label>
          <input size=5 id="expired_time_edt" name="expired_time_edt" type="text" value="" ></input>
          </p>

          <br/>

          <p>
          <label style="display: -moz-inline-box;" for="upd_file"><span style="display: block; width: 200px">\xd1\xee\xee\xe1\xf9\xe5\xed\xe8\xe5</span></label>
          <textarea style="width: 400px;" rows="5" name="content_txt" id="content_txt"></textarea>
          <br/>
          <br/>
          <div class="buttons">
            <button id=\'send_btn\' type="button"><img src="''')
        _v = VFFSL(SL,"eng_img",True) # '$eng_img' on line 39, col 59
        if _v is not None: write(_filter(_v, rawExpr='$eng_img')) # from line 39, col 59.
        write('''/actions/send.png"/>&nbsp;\xcf\xee\xf1\xeb\xe0\xf2\xfc</button>
          </div>
          </p>
      </fieldset>

    </form>
  </div>

  <div border=1 class="container" style="position:relative; float:left">
  <h5>\xca\xee\xed\xf1\xf2\xf0\xf3\xea\xf2\xee\xf0 \xf1\xee\xee\xe1\xf9\xe5\xed\xe8\xe9<h5>
      <br/>
      <div class="buttons">
        <button id=\'server_disabled_btn\' type="button"><img src="''')
        _v = VFFSL(SL,"eng_img",True) # '$eng_img' on line 51, col 66
        if _v is not None: write(_filter(_v, rawExpr='$eng_img')) # from line 51, col 66.
        write('''/actions/edit2.png"/>&nbsp;\xd1\xe5\xf0\xe2\xe5\xf0 \xed\xe5\xe4\xee\xf1\xf2\xf3\xef\xe5\xed</button>
        <select style="display: inline" id="time_disabled" style="width: 100px">
            <option value="5">5 \xec\xe8\xed</option>
            <option value="10">10 \xec\xe8\xed</option>
            <option value="15">15 \xec\xe8\xed</option>
            <option value="60">60 \xec\xe8\xed</option>
        </select>
        <br/>
        <br/>
        <button id=\'last_msg_btn\' type="button"><img src="''')
        _v = VFFSL(SL,"eng_img",True) # '$eng_img' on line 60, col 59
        if _v is not None: write(_filter(_v, rawExpr='$eng_img')) # from line 60, col 59.
        write('''/actions/edit2.png"/>&nbsp;\xcf\xee\xf1\xeb\xe5\xe4\xed\xe5\xe5 \xf1\xee\xee\xe1\xf9\xe5\xed\xe8\xe5</button>
      </div>
  </div>
</div>
<div id="status_div" border=1 class="container" style="clear: both">
</div>
''')
        # Scripts
        write('''<script type="text/javascript" src="''')
        _v = VFFSL(SL,"sp_js",True) # '$sp_js' on line 67, col 37
        if _v is not None: write(_filter(_v, rawExpr='$sp_js')) # from line 67, col 37.
        write('''/admin_send_msg.js"></script>
<script type="text/javascript" src="''')
        _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 68, col 37
        if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 68, col 37.
        write('''/utils.datetime.js"></script>

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_admin_send_msg= 'writeBody'

## END CLASS DEFINITION

if not hasattr(admin_send_msg, '_initCheetahAttributes'):
    templateAPIClass = getattr(admin_send_msg, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(admin_send_msg)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=admin_send_msg()).run()


