#!/usr/bin/env python
# -*- coding: cp1251 -*-



##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from systems.KURSSKLAD.cheetahutils import viewQuantity
from systems.KURSSKLAD.cheetahutils import Quantity
from systems.KURSSKLAD.KURSTERM.DOCFREESELECT.templates.taskWaresMain import taskWaresMain

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0rc8'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 8)
__CHEETAH_genTime__ = 1482336168.6670001
__CHEETAH_genTimestamp__ = 'Wed Dec 21 18:02:48 2016'
__CHEETAH_src__ = 'systems\\KURSSKLAD\\KURSTERM\\DOCFREESELECT\\templates\\UV\\taskWares.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Dec 21 09:10:13 2016'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class taskWares(taskWaresMain):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        taskWaresMain.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def waresRest(self, **KWS):



        ## CHEETAH: generated from #def waresRest at line 7, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''    <hr>
''')
        if VFFSL(SL,"varExists",False)('$datalist') and VFFSL(SL,"datalist",True): # generated from line 9, col 5
            write('''        <table>
            <thead>
                <tr>
                    <th>''')
            if False:
                _('МП')
            _v = VFFSL(SL,"_",False)('МП') # "$_('\xcc\xcf')" on line 13, col 25
            if _v is not None: write(_filter(_v, rawExpr="$_('\xcc\xcf')")) # from line 13, col 25.
            write('''</th>
                    <th>''')
            if False:
                _('КП')
            _v = VFFSL(SL,"_",False)('КП') # "$_('\xca\xcf')" on line 14, col 25
            if _v is not None: write(_filter(_v, rawExpr="$_('\xca\xcf')")) # from line 14, col 25.
            write('''</th>
                    <th>''')
            if False:
                _('Кол-во')
            _v = VFFSL(SL,"_",False)('Кол-во') # "$_('\xca\xee\xeb-\xe2\xee')" on line 15, col 25
            if _v is not None: write(_filter(_v, rawExpr="$_('\xca\xee\xeb-\xe2\xee')")) # from line 15, col 25.
            write('''</th>
                </tr>
            </thead>
''')
            q = 0
            write('''            <tbody>
''')
            for item in VFFSL(SL,"datalist",True): # generated from line 20, col 13
                q += VFFSL(SL,"item.AMOUNT",True)
                write('''                <tr>
                     <td><a href="#">''')
                _v = VFFSL(SL,"item.sname",True) # '$item.sname' on line 23, col 38
                if _v is not None: write(_filter(_v, rawExpr='$item.sname')) # from line 23, col 38.
                write('''</a></td>
''')
                if VFFSL(SL,"item.SPCODE",True) == 'S': # generated from line 24, col 20
                    write('''                     <td>0</td>
''')
                else: # generated from line 26, col 20
                    write('''                     <td>''')
                    _v = VFFSL(SL,"item.pcnt",True) # '$item.pcnt' on line 27, col 26
                    if _v is not None: write(_filter(_v, rawExpr='$item.pcnt')) # from line 27, col 26.
                    write('''</td>
''')
                write('''                     <td>''')
                _v = VFFSL(SL,"viewQuantity",False)(VFFSL(SL,"item.AMOUNT",True),VFFSL(SL,"VWUFACTOR",True),VFFSL(SL,"VWUCODE",True),VFFSL(SL,"MWUFACTOR",True),VFFSL(SL,"MWUCODE",True)) # '$viewQuantity($item.AMOUNT,$VWUFACTOR,$VWUCODE,$MWUFACTOR,$MWUCODE)' on line 29, col 26
                if _v is not None: write(_filter(_v, rawExpr='$viewQuantity($item.AMOUNT,$VWUFACTOR,$VWUCODE,$MWUFACTOR,$MWUCODE)')) # from line 29, col 26.
                write(''' <b>(<u>''')
                _v = VFFSL(SL,"Quantity",False)(VFFSL(SL,"item.amount",True)) # '$Quantity($item.amount)' on line 29, col 101
                if _v is not None: write(_filter(_v, rawExpr='$Quantity($item.amount)')) # from line 29, col 101.
                write('''</u>)</b></td>
                </tr>
''')
            write('''            </tbody>
            <tfoot>
                <tr>
                    <th colspan=3>''')
            _v = VFFSL(SL,"viewQuantity",False)(VFFSL(SL,"q",True),VFFSL(SL,"VWUFACTOR",True),VFFSL(SL,"VWUCODE",True),VFFSL(SL,"MWUFACTOR",True),VFFSL(SL,"MWUCODE",True)) # '$viewQuantity($q,$VWUFACTOR,$VWUCODE,$MWUFACTOR,$MWUCODE)' on line 35, col 35
            if _v is not None: write(_filter(_v, rawExpr='$viewQuantity($q,$VWUFACTOR,$VWUCODE,$MWUFACTOR,$MWUCODE)')) # from line 35, col 35.
            write(''' <b>(<u>''')
            _v = VFFSL(SL,"Quantity",False)(VFFSL(SL,"q",True)) # '$Quantity($q)' on line 35, col 100
            if _v is not None: write(_filter(_v, rawExpr='$Quantity($q)')) # from line 35, col 100.
            write('''</u>)</b></th>
                </tr>
            </tfoot>
        </table>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_taskWares= 'writeBody'

## END CLASS DEFINITION

if not hasattr(taskWares, '_initCheetahAttributes'):
    templateAPIClass = getattr(taskWares, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(taskWares)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=taskWares()).run()


