#!/usr/bin/env python
# -*- coding: cp1251 -*-



##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0rc8'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 8)
__CHEETAH_genTime__ = 1482336165.51
__CHEETAH_genTimestamp__ = 'Wed Dec 21 18:02:45 2016'
__CHEETAH_src__ = 'systems\\engine_main_term.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Dec 21 09:10:14 2016'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class engine_main_term(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def engineData_term(self, **KWS):



        ## CHEETAH: generated from #block engineData_term at line 140, col 9.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''            \xed\xe5\xf2 \xe8\xed\xf4\xee\xf0\xec\xe0\xf6\xe8\xe8 \xe4\xeb\xff \xee\xf2\xee\xe1\xf0\xe0\xe6\xe5\xed\xe8\xff
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="robots" content="noindex, nofollow">
''')
        if VFFSL(SL,"varExists",False)("system_name"): # generated from line 7, col 5
            write('''    <title>''')
            _v = VFFSL(SL,"system_name",True) # '$system_name' on line 8, col 12
            if _v is not None: write(_filter(_v, rawExpr='$system_name')) # from line 8, col 12.
            write('''</title>
''')
        if VFFSL(SL,"varExists",False)("eng_img"): # generated from line 10, col 5
            write('''    <link rel="shortcut icon" href="''')
            _v = VFFSL(SL,"eng_img",True) # '$eng_img' on line 11, col 37
            if _v is not None: write(_filter(_v, rawExpr='$eng_img')) # from line 11, col 37.
            write('''/favicon.ico">
''')
        write('''
    <link href="/locale/''')
        _v = VFFSL(SL,"getSesVar",False)('locale') # "$getSesVar('locale')" on line 14, col 25
        if _v is not None: write(_filter(_v, rawExpr="$getSesVar('locale')")) # from line 14, col 25.
        write('''/locale.json" lang="''')
        _v = VFFSL(SL,"getSesVar",False)('locale') # "$getSesVar('locale')" on line 14, col 65
        if _v is not None: write(_filter(_v, rawExpr="$getSesVar('locale')")) # from line 14, col 65.
        write('''" rel="gettext" />
    <script type="text/javascript" src="''')
        _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 15, col 41
        if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 15, col 41.
        write('''/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="''')
        _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 16, col 41
        if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 16, col 41.
        write('''/jquery.gettext.js"></script>
    <script type="text/javascript" src="''')
        _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 17, col 41
        if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 17, col 41.
        write('''/term/kTermEvents.js"></script>
    <script type="text/javascript" src="''')
        _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 18, col 41
        if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 18, col 41.
        write('''/term/kTermCommon.js"></script>

''')
        if VFFSL(SL,"varExists",False)("is_terminal") and VFFSL(SL,"is_terminal",True): # generated from line 20, col 5
            write('''        <link rel="stylesheet" href="''')
            _v = VFFSL(SL,"eng_css",True) # '$eng_css' on line 21, col 38
            if _v is not None: write(_filter(_v, rawExpr='$eng_css')) # from line 21, col 38.
            write('''/reset.css" type="text/css" media="screen"/>
        <link rel="stylesheet" href="''')
            _v = VFFSL(SL,"eng_css",True) # '$eng_css' on line 22, col 38
            if _v is not None: write(_filter(_v, rawExpr='$eng_css')) # from line 22, col 38.
            write('''/structure.css" type="text/css" media="screen"/>
        <link href="''')
            _v = VFFSL(SL,"eng_css",True) # '$eng_css' on line 23, col 21
            if _v is not None: write(_filter(_v, rawExpr='$eng_css')) # from line 23, col 21.
            write('''/terminal/main_term.css" rel="stylesheet" type="text/css" media="screen">
''')
        else: # generated from line 24, col 5
            write('''        <link rel="stylesheet" href="''')
            _v = VFFSL(SL,"eng_css",True) # '$eng_css' on line 25, col 38
            if _v is not None: write(_filter(_v, rawExpr='$eng_css')) # from line 25, col 38.
            write('''/reset.css" type="text/css" media="screen"/>
        <link rel="stylesheet" href="''')
            _v = VFFSL(SL,"eng_css",True) # '$eng_css' on line 26, col 38
            if _v is not None: write(_filter(_v, rawExpr='$eng_css')) # from line 26, col 38.
            write('''/structure.css" type="text/css" media="screen"/>
        <link rel="stylesheet" href="/ENGINE/css/datepicker.css" type="text/css" media="screen"/>
        <link href="''')
            _v = VFFSL(SL,"eng_css",True) # '$eng_css' on line 28, col 21
            if _v is not None: write(_filter(_v, rawExpr='$eng_css')) # from line 28, col 21.
            write('''/terminal/main_term_pk.css" rel="stylesheet" type="text/css" media="screen">
        <script type="text/javascript" src="''')
            _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 29, col 45
            if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 29, col 45.
            write('''/ui.datepicker.min.js"></script>
        <script type="text/javascript" src="''')
            _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 30, col 45
            if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 30, col 45.
            write('''/i18n/ui.datepicker-ru.js"></script>
        <script type="text/javascript" src="''')
            _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 31, col 45
            if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 31, col 45.
            write('''/jquery.maskedinput-1.2.1.pack.js"></script>
        <script type="text/javascript" src="''')
            _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 32, col 45
            if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 32, col 45.
            write('''/jquery.tablesorter.min.js"></script>
        <script type="text/javascript" src="''')
            _v = VFFSL(SL,"eng_js",True) # '$eng_js' on line 33, col 45
            if _v is not None: write(_filter(_v, rawExpr='$eng_js')) # from line 33, col 45.
            write('''/kTblScroll.min.js"></script>
''')
        write('''
    <script type="text/javascript">
    $(function(){

        $("<div id=\'container-busy\'></div>")
        .ajaxStart(function() {
            $(this).show();
            $(\'body\').addClass("cursor_wait");
        })
        .ajaxStop(function(){$(this).hide(); $(\'body\').removeClass("cursor_wait");})
        .ajaxError(function(event, request, settings, error){
''')
        # \$(this).text("Ошибка запроса страницы: " + settings.url).show();
        write('''            $(\'body\').removeClass("cursor_wait");
''')
        # alert("ajaxError: Во время обработки запроса возникла ошибка, либо пропала связь с сервером! Администратор системы автоматически получит электронное письмо. Попробуйте подключиться через 5-10 минут.");
        write('''            try {
                eval("var json=" + request.responseText);
            }
            catch(e) {
                var json = request.responseText;
            }
            var mes = (json ? \'\\n\\n\\n\xd2\xe5\xf5\xed\xe8\xf7\xe5\xf1\xea\xe8\xe5 \xef\xee\xe4\xf0\xee\xe1\xed\xee\xf1\xf2\xe8:\\n---\\n\' + (json.mes ? json.mes : json) : \'\');
            alert(\'\xc2\xee \xe2\xf0\xe5\xec\xff \xee\xe1\xf0\xe0\xe1\xee\xf2\xea\xe8 \xe7\xe0\xef\xf0\xee\xf1\xe0 \xe2\xee\xe7\xed\xe8\xea\xeb\xe0 \xee\xf8\xe8\xe1\xea\xe0 \xeb\xe8\xe1\xee \xef\xf0\xee\xef\xe0\xeb\xe0 \xf1\xe2\xff\xe7\xfc \xf1 \xf1\xe5\xf0\xe2\xe5\xf0\xee\xec:\' + mes);
''')
        # alert(listProperties(request, 'request'));
        write('''        })
        .appendTo("#container-head");
    });
    </script>

</head>
<body>
''')
        # <script>
        #     ## string params
        #     #if $varExists('$sp')
        #       sp="$sp";
        #     #end if
        #     #if $varExists('$sp_img')
        #       sp_img="$sp_img";
        #     #end if
        #     #if $varExists('$sp_css')
        #       sp_css="$sp_css";
        #     #end if
        #     #if $varExists('$sp_js')
        #       sp_js="$sp_js";
        #     #end if
        #     #if $varExists('$sp_forms')
        #       sp_forms="$sp_forms";
        #     #end if
        #     #if $varExists('$sp_reports')
        #       sp_reports="$sp_reports";
        #     #end if
        # 
        #     eng_img="$eng_img";
        #     eng_css="$eng_css";
        #     eng_js="$eng_js";
        #     eng_forms="$eng_forms";
        #     eng_reports="$eng_reports";
        # 
        #     ## dict params
        #     sps_name=$sps_name;
        #     ##sps_img=$sps_img;
        #     sps_css=$sps_css;
        #     sps_js=$sps_js;
        #     sps_forms=$sps_forms;
        #     sps_reports=$sps_reports;
        # 
        #     function include(script_filename) {
        #       document.write('<'+'script'+' language="javascript"'+' type="text/javascript"'+' src="'+script_filename+'">'+'</'+'script'+'>');
        #     }
        # </script>
        write('''<script>
''')
        if VFFSL(SL,"varExists",False)('$sp_img'): # generated from line 105, col 5
            write('''      sp_img="''')
            _v = VFFSL(SL,"sp_img",True) # '$sp_img' on line 106, col 15
            if _v is not None: write(_filter(_v, rawExpr='$sp_img')) # from line 106, col 15.
            write('''";
''')
        write('''    sps_img="''')
        _v = VFFSL(SL,"sps_img.KURSTERM",True) # '$sps_img.KURSTERM' on line 108, col 14
        if _v is not None: write(_filter(_v, rawExpr='$sps_img.KURSTERM')) # from line 108, col 14.
        write('''";
</script>

  <div id="container-page">
    <!--Begin Head -->
    <div id="container-head" class="container">
''')
        if VFFSL(SL,"varExists",False)("OBJECT_NAME"): # generated from line 114, col 9
            write('''        <div id="shop_number">
            ''')
            _v = VFFSL(SL,"OBJECT_NAME",True) # '$OBJECT_NAME' on line 116, col 13
            if _v is not None: write(_filter(_v, rawExpr='$OBJECT_NAME')) # from line 116, col 13.
            write('''
        </div>
''')
        write('''
''')
        if VFFSL(SL,"varExists",False)("userfio"): # generated from line 120, col 9
            write('''            <div id="userfio">
                ''')
            _v = VFFSL(SL,"userfio",True) # '$userfio' on line 122, col 17
            if _v is not None: write(_filter(_v, rawExpr='$userfio')) # from line 122, col 17.
            write('''
            </div>
''')
        write('''        <div id="icons">
            <ul class="user-menu">
''')
        # <li><a href="tasklist" title="Меню"><img src="$eng_img/terminal/menu.bmp" alt="Меню"></a></li>
        write('''               <li><a href="exit"title="\xc2\xfb\xf5\xee\xe4"><img  src="''')
        _v = VFFSL(SL,"eng_img",True) # '$eng_img' on line 128, col 59
        if _v is not None: write(_filter(_v, rawExpr='$eng_img')) # from line 128, col 59.
        write('''/terminal/exit.bmp" alt="\xc2\xfb\xf5\xee\xe4"></a><li>
            </ul>
        </div>

''')
        if VFFSL(SL,"varExists",False)("system_name"): # generated from line 132, col 9
            write('''          <div id="sys-name">''')
            _v = VFFSL(SL,"system_name",True) # '$system_name' on line 133, col 30
            if _v is not None: write(_filter(_v, rawExpr='$system_name')) # from line 133, col 30.
            write('''</div>
''')
        write('''    </div>

    <div id="container-content-wrapper">
      <div id="container-content" class="container" align="center">
        <!--Begin Interface Data-->
''')
        self.engineData_term(trans=trans)
        write('''        <!--End Interface Data-->
      </div>
    </div>
  </div>
  <div id="container-footer" class="container">
    <div id="dvStatus"></div>
    <div id="dvButtons"></div>
  </div>
</body>
</html>




''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_engine_main_term= 'respond'

## END CLASS DEFINITION

if not hasattr(engine_main_term, '_initCheetahAttributes'):
    templateAPIClass = getattr(engine_main_term, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(engine_main_term)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=engine_main_term()).run()


