#!/usr/bin/env python
# -*- coding: cp1251 -*-



##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from datetime_utils import formatMxDateTime

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0rc8'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 8)
__CHEETAH_genTime__ = 1482336166.9119999
__CHEETAH_genTimestamp__ = 'Wed Dec 21 18:02:46 2016'
__CHEETAH_src__ = 'systems\\ENGINE\\HEALTH\\templates\\health_blocks.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Dec 21 09:10:13 2016'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class health_blocks(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        dateformat = '%d.%m.%Y %H:%M:%S'
        refresh = VFFSL(SL,"eng_img",True)+"/actions/refresh.png"
        refresht = "Обновить"
        # set $refreshbtn="<a href='#' class='refresh' title="+$refresht+" ><img src="+$refresh+" alt="+$refresht+" /></a>"
        refreshbtn = ""
        statt = "Статистика"
        calct = "Расчет"
        taskst = "Заданий"
        lastdatet = "Дата последнего выполненного задания"
        allt = "всего"
        offt = "посчитано"
        ont = "осталось"
        activet = "активно"
        errt = "ошибки"
        processort = "Процессор"
        ramt = "ОЗУ"
        hddt = "Жесткий диск"
        servertimet = "Время"
        serverauserst = "Пользователей"
        transt = "Транзакций"
        threadst = "Потоки"
        detailt = "Детализация"
        detailsrc = "/KURS/images/info.png"
        detailbtn = "<a href='#' class='detail' title="+VFFSL(SL,"detailt",True)+"><img src="+VFFSL(SL,"detailsrc",True)+" alt="+VFFSL(SL,"detailt",True)+" /></a>"
        transfert = "Перебросить"
        transfersrc = "/KURS/images/arrow_up_down.png"
        transferbtn = "<a href='#' class='transfer' title="+VFFSL(SL,"transfert",True)+"><img src="+VFFSL(SL,"transfersrc",True)+" alt="+VFFSL(SL,"transfert",True)+" /></a>"
        write('''
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'PYTHON': # generated from line 31, col 1
            write('''    <div class="row PYTHON">
''')
            if VFFSL(SL,"is_linux",True): # generated from line 33, col 9
                Class_Health = 'HealthGood'
                if float(VFFSL(SL,"PYTHON_CPU",True))>30: # generated from line 35, col 13
                    Class_Health = 'HealthBad'
                write('''            <table><tr>
                <th colspan="4">\xcf\xf0\xee\xf6\xe5\xf1\xf1\xee\xf0 ''')
                _v = VFFSL(SL,"refreshbtn",True) # '$refreshbtn' on line 39, col 43
                if _v is not None: write(_filter(_v, rawExpr='$refreshbtn')) # from line 39, col 43.
                write('''</th>
                </tr><tr>
                <td class="Label ''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 41, col 34
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 41, col 34.
                write('''">''')
                _v = VFFSL(SL,"processort",True) # '$processort' on line 41, col 49
                if _v is not None: write(_filter(_v, rawExpr='$processort')) # from line 41, col 49.
                write(''':</td>
                <td title="''')
                _v = VFFSL(SL,"allt",True) # '$allt' on line 42, col 28
                if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 42, col 28.
                write('''" class="''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 42, col 42
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 42, col 42.
                write('''">''')
                _v = VFFSL(SL,"PYTHON_CPU",True) # '$PYTHON_CPU' on line 42, col 57
                if _v is not None: write(_filter(_v, rawExpr='$PYTHON_CPU')) # from line 42, col 57.
                write('''%</td>
                <td class="Label">''')
                _v = VFFSL(SL,"ramt",True) # '$ramt' on line 43, col 35
                if _v is not None: write(_filter(_v, rawExpr='$ramt')) # from line 43, col 35.
                write('''</td>
                <td title="''')
                _v = VFFSL(SL,"ont",True) # '$ont' on line 44, col 28
                if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 44, col 28.
                write('''" class="Label">''')
                _v = VFFSL(SL,"PYTHON_RAM",True) # '$PYTHON_RAM' on line 44, col 48
                if _v is not None: write(_filter(_v, rawExpr='$PYTHON_RAM')) # from line 44, col 48.
                write('''%</td>
            </tr></table>
''')
            Class_Health = 'HealthGood'
            if VFFSL(SL,"PYTHON_THREADS",True)>VFFSL(SL,"PYTHON_ACTIVE_THREADS",True): # generated from line 48, col 9
                Class_Health = 'HealthBad'
            write('''        <table><tr>
            <th colspan="3">\xd1\xe5\xf0\xe2\xe5\xf0 ''')
            _v = VFFSL(SL,"refreshbtn",True) # '$refreshbtn' on line 52, col 36
            if _v is not None: write(_filter(_v, rawExpr='$refreshbtn')) # from line 52, col 36.
            write('''</th>
            </tr><tr>
            <td class="Label">''')
            _v = VFFSL(SL,"servertimet",True) # '$servertimet' on line 54, col 31
            if _v is not None: write(_filter(_v, rawExpr='$servertimet')) # from line 54, col 31.
            write(''':</td>
            <td colspan="2" class="Label">''')
            _v = VFFSL(SL,"PYTHON_SERVER_TIME",True) # '$PYTHON_SERVER_TIME' on line 55, col 43
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_SERVER_TIME')) # from line 55, col 43.
            write('''</td>
            </tr><tr>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 57, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 57, col 30.
            write('''">''')
            _v = VFFSL(SL,"threadst",True) # '$threadst' on line 57, col 45
            if _v is not None: write(_filter(_v, rawExpr='$threadst')) # from line 57, col 45.
            write(''':</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 58, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 58, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"PYTHON_THREADS",True) # '$PYTHON_THREADS' on line 58, col 48
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_THREADS')) # from line 58, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"activet",True) # '$activet' on line 59, col 24
            if _v is not None: write(_filter(_v, rawExpr='$activet')) # from line 59, col 24.
            write('''" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 59, col 41
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 59, col 41.
            write('''">''')
            _v = VFFSL(SL,"PYTHON_ACTIVE_THREADS",True) # '$PYTHON_ACTIVE_THREADS' on line 59, col 56
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_ACTIVE_THREADS')) # from line 59, col 56.
            write('''</td>
            </tr><tr>
            <td class="Label">''')
            _v = VFFSL(SL,"serverauserst",True) # '$serverauserst' on line 61, col 31
            if _v is not None: write(_filter(_v, rawExpr='$serverauserst')) # from line 61, col 31.
            write(''':</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 62, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 62, col 24.
            write('''" class="Label">''')
            _v = VFFSL(SL,"PYTHON_COUNT_USERS",True) # '$PYTHON_COUNT_USERS' on line 62, col 45
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_COUNT_USERS')) # from line 62, col 45.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"activet",True) # '$activet' on line 63, col 24
            if _v is not None: write(_filter(_v, rawExpr='$activet')) # from line 63, col 24.
            write('''" class="Label">''')
            _v = VFFSL(SL,"PYTHON_COUNT_ACTIVE_USERS",True) # '$PYTHON_COUNT_ACTIVE_USERS' on line 63, col 48
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_COUNT_ACTIVE_USERS')) # from line 63, col 48.
            write('''</td>
            </tr><tr>
''')
            Class_Health = 'HealthGood'
            if VFFSL(SL,"PYTHON_ACTIVE_TRANS",True)>10: # generated from line 66, col 13
                Class_Health = 'HealthBad'
            write('''            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 69, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 69, col 30.
            write('''">''')
            _v = VFFSL(SL,"transt",True) # '$transt' on line 69, col 45
            if _v is not None: write(_filter(_v, rawExpr='$transt')) # from line 69, col 45.
            write(''':</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 70, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 70, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"PYTHON_TRANS",True) # '$PYTHON_TRANS' on line 70, col 48
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_TRANS')) # from line 70, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"activet",True) # '$activet' on line 71, col 24
            if _v is not None: write(_filter(_v, rawExpr='$activet')) # from line 71, col 24.
            write('''" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 71, col 41
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 71, col 41.
            write('''">''')
            _v = VFFSL(SL,"PYTHON_ACTIVE_TRANS",True) # '$PYTHON_ACTIVE_TRANS' on line 71, col 56
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_ACTIVE_TRANS')) # from line 71, col 56.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'SALE': # generated from line 75, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_SALE_TASKS_ON",True) > 0: # generated from line 77, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row SALE">
        <table><tr>
            <th colspan="6">\xce\xed\xeb\xe0\xe9\xed \xef\xf0\xee\xe4\xe0\xe6\xe8 ''')
            _v = VFFSL(SL,"refreshbtn",True) # '$refreshbtn' on line 82, col 44
            if _v is not None: write(_filter(_v, rawExpr='$refreshbtn')) # from line 82, col 44.
            write('''</th>
            </tr><tr>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 84, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 84, col 30.
            write('''">''')
            _v = VFFSL(SL,"taskst",True) # '$taskst' on line 84, col 45
            if _v is not None: write(_filter(_v, rawExpr='$taskst')) # from line 84, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 85, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 85, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 85, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 85, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_SALE_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_SALE_TASKS_OFF,$dateformat)' on line 85, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_SALE_TASKS_OFF,$dateformat)')) # from line 85, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 86, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 86, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_SALE_TASKS",True) # '$CNT_SALE_TASKS' on line 86, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SALE_TASKS')) # from line 86, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 87, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 87, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_SALE_TASKS_OFF",True) # '$CNT_SALE_TASKS_OFF' on line 87, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SALE_TASKS_OFF')) # from line 87, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 88, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 88, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_SALE_TASKS_ERR",True) # '$CNT_SALE_TASKS_ERR' on line 88, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SALE_TASKS_ERR')) # from line 88, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 89, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 89, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_SALE_TASKS_ON",True) # '$CNT_SALE_TASKS_ON' on line 89, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SALE_TASKS_ON')) # from line 89, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'PACKET': # generated from line 93, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_PACKET_TASKS_ON",True) > 0: # generated from line 95, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row PACKET">
        <table><tr>
            <th colspan="6">\xc2\xfb\xe3\xf0\xf3\xe7\xea\xe0 \xef\xe0\xea\xe5\xf2\xee\xe2 ''')
            _v = VFFSL(SL,"refreshbtn",True) # '$refreshbtn' on line 100, col 46
            if _v is not None: write(_filter(_v, rawExpr='$refreshbtn')) # from line 100, col 46.
            write('''</th>
            </tr><tr>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 102, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 102, col 30.
            write('''">''')
            _v = VFFSL(SL,"taskst",True) # '$taskst' on line 102, col 45
            if _v is not None: write(_filter(_v, rawExpr='$taskst')) # from line 102, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 103, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 103, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 103, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 103, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_PACKET_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_PACKET_TASKS_OFF,$dateformat)' on line 103, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_PACKET_TASKS_OFF,$dateformat)')) # from line 103, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 104, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 104, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_PACKET_TASKS",True) # '$CNT_PACKET_TASKS' on line 104, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PACKET_TASKS')) # from line 104, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 105, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 105, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_PACKET_TASKS_OFF",True) # '$CNT_PACKET_TASKS_OFF' on line 105, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PACKET_TASKS_OFF')) # from line 105, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 106, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 106, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_PACKET_TASKS_ERR",True) # '$CNT_PACKET_TASKS_ERR' on line 106, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PACKET_TASKS_ERR')) # from line 106, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 107, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 107, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_PACKET_TASKS_ON",True) # '$CNT_PACKET_TASKS_ON' on line 107, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PACKET_TASKS_ON')) # from line 107, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'AORDERSTAT': # generated from line 111, col 1
            write('''    <div class="row AORDERSTAT">
        <table><tr>
            <th colspan="6">\xd1\xf2\xe0\xf2\xe8\xf1\xf2\xe8\xea\xe0 \xe0\xe2\xf2\xee\xe7\xe0\xea\xe0\xe7\xe0 ''')
            _v = VFFSL(SL,"refreshbtn",True) # '$refreshbtn' on line 114, col 51
            if _v is not None: write(_filter(_v, rawExpr='$refreshbtn')) # from line 114, col 51.
            write('''</th>
            </tr><tr>
''')
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_AORDERSTAT_TASKS_ON",True) > 0: # generated from line 117, col 13
                Class_Health = 'HealthBad'
            write('''            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 120, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 120, col 30.
            write('''">''')
            _v = VFFSL(SL,"statt",True) # '$statt' on line 120, col 45
            if _v is not None: write(_filter(_v, rawExpr='$statt')) # from line 120, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 121, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 121, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 121, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 121, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_AORDERSTAT_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_AORDERSTAT_TASKS_OFF,$dateformat)' on line 121, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_AORDERSTAT_TASKS_OFF,$dateformat)')) # from line 121, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 122, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 122, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_AORDERSTAT_TASKS",True) # '$CNT_AORDERSTAT_TASKS' on line 122, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDERSTAT_TASKS')) # from line 122, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 123, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 123, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_AORDERSTAT_TASKS_OFF",True) # '$CNT_AORDERSTAT_TASKS_OFF' on line 123, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDERSTAT_TASKS_OFF')) # from line 123, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 124, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 124, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_AORDERSTAT_TASKS_ERR",True) # '$CNT_AORDERSTAT_TASKS_ERR' on line 124, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDERSTAT_TASKS_ERR')) # from line 124, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 125, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 125, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_AORDERSTAT_TASKS_ON",True) # '$CNT_AORDERSTAT_TASKS_ON' on line 125, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDERSTAT_TASKS_ON')) # from line 125, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'AORDER': # generated from line 129, col 1
            write('''    <div class="row AORDER">
        <table><tr>
            <th colspan="6">\xd0\xe0\xf1\xf7\xe5\xf2 \xe0\xe2\xf2\xee\xe7\xe0\xea\xe0\xe7\xe0 ''')
            _v = VFFSL(SL,"refreshbtn",True) # '$refreshbtn' on line 132, col 47
            if _v is not None: write(_filter(_v, rawExpr='$refreshbtn')) # from line 132, col 47.
            write(''' </th>
            </tr><tr>
''')
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_AORDER_TASKS_ON",True) > 0: # generated from line 135, col 13
                Class_Health = 'HealthBad'
            write('''            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 138, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 138, col 30.
            write('''">''')
            _v = VFFSL(SL,"calct",True) # '$calct' on line 138, col 45
            if _v is not None: write(_filter(_v, rawExpr='$calct')) # from line 138, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 139, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 139, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 139, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 139, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_AORDER_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_AORDER_TASKS_OFF,$dateformat)' on line 139, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_AORDER_TASKS_OFF,$dateformat)')) # from line 139, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 140, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 140, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_AORDER_TASKS",True) # '$CNT_AORDER_TASKS' on line 140, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDER_TASKS')) # from line 140, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 141, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 141, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_AORDER_TASKS_OFF",True) # '$CNT_AORDER_TASKS_OFF' on line 141, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDER_TASKS_OFF')) # from line 141, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 142, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 142, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_AORDER_TASKS_ERR",True) # '$CNT_AORDER_TASKS_ERR' on line 142, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDER_TASKS_ERR')) # from line 142, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 143, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 143, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_AORDER_TASKS_ON",True) # '$CNT_AORDER_TASKS_ON' on line 143, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDER_TASKS_ON')) # from line 143, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'RORDER': # generated from line 147, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_RORDER_TASKS_ON",True) > 0: # generated from line 149, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row RORDER">
        <table><tr>
            <th colspan="6">\xd0\xee\xf1\xef\xe8\xf1\xfc ''')
            _v = VFFSL(SL,"refreshbtn",True) # '$refreshbtn' on line 154, col 37
            if _v is not None: write(_filter(_v, rawExpr='$refreshbtn')) # from line 154, col 37.
            write('''</th>
            </tr><tr>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 156, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 156, col 30.
            write('''">''')
            _v = VFFSL(SL,"taskst",True) # '$taskst' on line 156, col 45
            if _v is not None: write(_filter(_v, rawExpr='$taskst')) # from line 156, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 157, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 157, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 157, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 157, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_RORDER_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_RORDER_TASKS_OFF,$dateformat)' on line 157, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_RORDER_TASKS_OFF,$dateformat)')) # from line 157, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 158, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 158, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_RORDER_TASKS",True) # '$CNT_RORDER_TASKS' on line 158, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_RORDER_TASKS')) # from line 158, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 159, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 159, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_RORDER_TASKS_OFF",True) # '$CNT_RORDER_TASKS_OFF' on line 159, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_RORDER_TASKS_OFF')) # from line 159, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 160, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 160, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_RORDER_TASKS_ERR",True) # '$CNT_RORDER_TASKS_ERR' on line 160, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_RORDER_TASKS_ERR')) # from line 160, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 161, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 161, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_RORDER_TASKS_ON",True) # '$CNT_RORDER_TASKS_ON' on line 161, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_RORDER_TASKS_ON')) # from line 161, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'PRICING': # generated from line 165, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_PRICING_TASKS_ON",True) > 0: # generated from line 167, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row PRICING">
        <table><tr>
            <th colspan="6">\xd6\xe5\xed\xee\xee\xe1\xf0\xe0\xe7\xee\xe2\xe0\xed\xe8\xe5 ''')
            _v = VFFSL(SL,"detailbtn",True) # '$detailbtn' on line 172, col 45
            if _v is not None: write(_filter(_v, rawExpr='$detailbtn')) # from line 172, col 45.
            write('''</th>
            </tr><tr>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 174, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 174, col 30.
            write('''">''')
            _v = VFFSL(SL,"taskst",True) # '$taskst' on line 174, col 45
            if _v is not None: write(_filter(_v, rawExpr='$taskst')) # from line 174, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 175, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 175, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 175, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 175, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_PRICING_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_PRICING_TASKS_OFF,$dateformat)' on line 175, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_PRICING_TASKS_OFF,$dateformat)')) # from line 175, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 176, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 176, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_PRICING_TASKS",True) # '$CNT_PRICING_TASKS' on line 176, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PRICING_TASKS')) # from line 176, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 177, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 177, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_PRICING_TASKS_OFF",True) # '$CNT_PRICING_TASKS_OFF' on line 177, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PRICING_TASKS_OFF')) # from line 177, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 178, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 178, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_PRICING_TASKS_ERR",True) # '$CNT_PRICING_TASKS_ERR' on line 178, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PRICING_TASKS_ERR')) # from line 178, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 179, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 179, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_PRICING_TASKS_ON",True) # '$CNT_PRICING_TASKS_ON' on line 179, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PRICING_TASKS_ON')) # from line 179, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'WSETPRLIST': # generated from line 183, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_WSETPRLIST_TASKS_ON",True) > 0: # generated from line 185, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row WSETPRLIST">
        <table><tr>
            <th colspan="6">\xcf\xf0\xe0\xe9\xf1-\xeb\xe8\xf1\xf2\xfb ''')
            _v = VFFSL(SL,"detailbtn",True) # '$detailbtn' on line 190, col 41
            if _v is not None: write(_filter(_v, rawExpr='$detailbtn')) # from line 190, col 41.
            write('''</th>
            </tr><tr>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 192, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 192, col 30.
            write('''">''')
            _v = VFFSL(SL,"taskst",True) # '$taskst' on line 192, col 45
            if _v is not None: write(_filter(_v, rawExpr='$taskst')) # from line 192, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 193, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 193, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 193, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 193, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_WSETPRLIST_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_WSETPRLIST_TASKS_OFF,$dateformat)' on line 193, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_WSETPRLIST_TASKS_OFF,$dateformat)')) # from line 193, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 194, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 194, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_WSETPRLIST_TASKS",True) # '$CNT_WSETPRLIST_TASKS' on line 194, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_WSETPRLIST_TASKS')) # from line 194, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 195, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 195, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_WSETPRLIST_TASKS_OFF",True) # '$CNT_WSETPRLIST_TASKS_OFF' on line 195, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_WSETPRLIST_TASKS_OFF')) # from line 195, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 196, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 196, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_WSETPRLIST_TASKS_ERR",True) # '$CNT_WSETPRLIST_TASKS_ERR' on line 196, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_WSETPRLIST_TASKS_ERR')) # from line 196, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 197, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 197, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_WSETPRLIST_TASKS_ON",True) # '$CNT_WSETPRLIST_TASKS_ON' on line 197, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_WSETPRLIST_TASKS_ON')) # from line 197, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'SHARE': # generated from line 201, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_SHARE_TASKS_ON",True) > 0: # generated from line 203, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row SHARE">
        <table><tr>
            <th colspan="6">\xc0\xea\xf6\xe8\xe8 ''')
            _v = VFFSL(SL,"detailbtn",True) # '$detailbtn' on line 208, col 35
            if _v is not None: write(_filter(_v, rawExpr='$detailbtn')) # from line 208, col 35.
            write('''</th>
            </tr><tr>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 210, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 210, col 30.
            write('''">''')
            _v = VFFSL(SL,"taskst",True) # '$taskst' on line 210, col 45
            if _v is not None: write(_filter(_v, rawExpr='$taskst')) # from line 210, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 211, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 211, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 211, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 211, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_SHARE_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_SHARE_TASKS_OFF,$dateformat)' on line 211, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_SHARE_TASKS_OFF,$dateformat)')) # from line 211, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 212, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 212, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_SHARE_TASKS",True) # '$CNT_SHARE_TASKS' on line 212, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SHARE_TASKS')) # from line 212, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 213, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 213, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_SHARE_TASKS_OFF",True) # '$CNT_SHARE_TASKS_OFF' on line 213, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SHARE_TASKS_OFF')) # from line 213, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 214, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 214, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_SHARE_TASKS_ERR",True) # '$CNT_SHARE_TASKS_ERR' on line 214, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SHARE_TASKS_ERR')) # from line 214, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 215, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 215, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_SHARE_TASKS_ON",True) # '$CNT_SHARE_TASKS_ON' on line 215, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SHARE_TASKS_ON')) # from line 215, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'MAINSUPPLIERS': # generated from line 219, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS_ON",True) > 0: # generated from line 221, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row MAINSUPPLIERS">
        <table><tr>
            <th colspan="6">\xce\xf1\xed\xee\xe2\xed\xee\xe9 \xef\xee\xf1\xf2\xe0\xe2\xf9\xe8\xea ''')
            _v = VFFSL(SL,"detailbtn",True) # '$detailbtn' on line 226, col 48
            if _v is not None: write(_filter(_v, rawExpr='$detailbtn')) # from line 226, col 48.
            write('''</th>
            </tr><tr>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 228, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 228, col 30.
            write('''">''')
            _v = VFFSL(SL,"taskst",True) # '$taskst' on line 228, col 45
            if _v is not None: write(_filter(_v, rawExpr='$taskst')) # from line 228, col 45.
            write(''':</td>
            <td class="Label ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 229, col 30
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 229, col 30.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 229, col 52
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 229, col 52.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_MAINSUPPLIERS_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_MAINSUPPLIERS_TASKS_OFF,$dateformat)' on line 229, col 64
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_MAINSUPPLIERS_TASKS_OFF,$dateformat)')) # from line 229, col 64.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 230, col 24
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 230, col 24.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS",True) # '$CNT_MAINSUPPLIERS_TASKS' on line 230, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_MAINSUPPLIERS_TASKS')) # from line 230, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 231, col 24
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 231, col 24.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS_OFF",True) # '$CNT_MAINSUPPLIERS_TASKS_OFF' on line 231, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_MAINSUPPLIERS_TASKS_OFF')) # from line 231, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 232, col 24
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 232, col 24.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS_ERR",True) # '$CNT_MAINSUPPLIERS_TASKS_ERR' on line 232, col 48
            if _v is not None: write(_filter(_v, rawExpr='$CNT_MAINSUPPLIERS_TASKS_ERR')) # from line 232, col 48.
            write('''</td>
            <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 233, col 24
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 233, col 24.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS_ON",True) # '$CNT_MAINSUPPLIERS_TASKS_ON' on line 233, col 46
            if _v is not None: write(_filter(_v, rawExpr='$CNT_MAINSUPPLIERS_TASKS_ON')) # from line 233, col 46.
            write('''</td>
        </tr></table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) is None or VFFSL(SL,"refresh_block",True) == 'ROBOTS': # generated from line 237, col 1
            if not VFFSL(SL,"opt",False)('grant',None,'transfer','other'): # generated from line 238, col 5
                transferbtn = ''
            write('''    <div class="row ROBOTS">
        <table>
            <tr><th colspan="5">\xd0\xee\xe1\xee\xf2\xfb \xef\xe5\xf0\xe5\xee\xf6\xe5\xed\xea\xe8 ''')
            _v = VFFSL(SL,"transferbtn",True) # '$transferbtn' on line 243, col 51
            if _v is not None: write(_filter(_v, rawExpr='$transferbtn')) # from line 243, col 51.
            write('''</th></tr>
''')
            for item in VFFSL(SL,"datalist",True): # generated from line 244, col 13
                Class_Health = 'HealthGood'
                if VFFSL(SL,"item.CNT_ROBOT_TASKS_ON",True) > 0: # generated from line 246, col 17
                    Class_Health = 'HealthBad'
                write('''                <tr id="QUEUETASKID-''')
                _v = VFFSL(SL,"item.R_QUEUETASKID",True) # '$item.R_QUEUETASKID' on line 249, col 37
                if _v is not None: write(_filter(_v, rawExpr='$item.R_QUEUETASKID')) # from line 249, col 37.
                write('''">
                    <td class="Label ''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 250, col 38
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 250, col 38.
                write('''" title="IP \xf0\xee\xe1\xee\xf2\xe0" colspan="1" rowspan="2">''')
                _v = VFFSL(SL,"item.IP_ROBOT",True) # '$item.IP_ROBOT' on line 250, col 95
                if _v is not None: write(_filter(_v, rawExpr='$item.IP_ROBOT')) # from line 250, col 95.
                write('''</td>
                    <td title="''')
                _v = VFFSL(SL,"allt",True) # '$allt' on line 251, col 32
                if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 251, col 32.
                write('''" class="AllTasks">''')
                _v = VFFSL(SL,"item.CNT_ROBOT_TASKS",True) # '$item.CNT_ROBOT_TASKS' on line 251, col 56
                if _v is not None: write(_filter(_v, rawExpr='$item.CNT_ROBOT_TASKS')) # from line 251, col 56.
                write('''</td>
                    <td title="''')
                _v = VFFSL(SL,"offt",True) # '$offt' on line 252, col 32
                if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 252, col 32.
                write('''" class="OffTasks">''')
                _v = VFFSL(SL,"item.CNT_ROBOT_TASKS_OFF",True) # '$item.CNT_ROBOT_TASKS_OFF' on line 252, col 56
                if _v is not None: write(_filter(_v, rawExpr='$item.CNT_ROBOT_TASKS_OFF')) # from line 252, col 56.
                write('''</td>
                    <td title="''')
                _v = VFFSL(SL,"errt",True) # '$errt' on line 253, col 32
                if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 253, col 32.
                write('''" class="ErrTasks">''')
                _v = VFFSL(SL,"item.CNT_ROBOT_TASKS_ERR",True) # '$item.CNT_ROBOT_TASKS_ERR' on line 253, col 56
                if _v is not None: write(_filter(_v, rawExpr='$item.CNT_ROBOT_TASKS_ERR')) # from line 253, col 56.
                write('''</td>
                    <td title="''')
                _v = VFFSL(SL,"ont",True) # '$ont' on line 254, col 32
                if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 254, col 32.
                write('''" class="OnTasks">''')
                _v = VFFSL(SL,"item.CNT_ROBOT_TASKS_ON",True) # '$item.CNT_ROBOT_TASKS_ON' on line 254, col 54
                if _v is not None: write(_filter(_v, rawExpr='$item.CNT_ROBOT_TASKS_ON')) # from line 254, col 54.
                write('''</td>
                </tr>
                <tr><td class="LastDate ''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 256, col 41
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 256, col 41.
                write('''" title="''')
                _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 256, col 63
                if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 256, col 63.
                write('''" colspan="4" rowspan="1">''')
                _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"item.LD_ROBOT_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($item.LD_ROBOT_TASKS_OFF,$dateformat)' on line 256, col 99
                if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($item.LD_ROBOT_TASKS_OFF,$dateformat)')) # from line 256, col 99.
                write('''</td></tr>
''')
            write('''        </table>
    </div>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_health_blocks= 'respond'

## END CLASS DEFINITION

if not hasattr(health_blocks, '_initCheetahAttributes'):
    templateAPIClass = getattr(health_blocks, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(health_blocks)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=health_blocks()).run()


