#!/usr/bin/env python
# -*- coding: cp1251 -*-



##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from datetime_utils import formatMxDateTime

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0rc8'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 8)
__CHEETAH_genTime__ = 1482336167.0799999
__CHEETAH_genTimestamp__ = 'Wed Dec 21 18:02:47 2016'
__CHEETAH_src__ = 'systems\\ENGINE\\HEALTH\\templates\\health_blocks_mobile.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Dec 21 09:10:13 2016'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class health_blocks_mobile(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        dateformat = '%d.%m.%Y %H:%M:%S'
        refresh = VFFSL(SL,"eng_img",True)+"/actions/refresh.png"
        statt = "Статистика"
        calct = "Расчет"
        taskst = "Заданий"
        lastdatet = "Дата последнего выполненного задания"
        allt = "всего"
        offt = "посчитано"
        ont = "осталось"
        activet = "активно"
        errt = "ошибки"
        processort = "Процессор"
        ramt = "ОЗУ"
        hddt = "Жесткий диск"
        servertimet = "Время"
        serverauserst = "Пользователей"
        transt = "Транзакций"
        threadst = "Потоки"
        write('''
''')
        if VFFSL(SL,"refresh_block",True) == 'PYTHON': # generated from line 22, col 1
            write('''    <div class="row PYTHON">
''')
            if VFFSL(SL,"is_linux",True): # generated from line 24, col 9
                Class_Health = 'HealthGood'
                if float(VFFSL(SL,"PYTHON_CPU",True))>30: # generated from line 26, col 13
                    Class_Health = 'HealthBad'
                if VFFSL(SL,"PYTHON_THREADS",True)>VFFSL(SL,"PYTHON_ACTIVE_THREADS",True): # generated from line 29, col 13
                    Class_Health = 'HealthBad'
                write('''            <table>
                <tr><td rowspan="7" class="logo ''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 33, col 49
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 33, col 49.
                write('''"></td><th colspan="3" rowspan="1">\xcf\xf0\xee\xf6\xe5\xf1\xf1\xee\xf0</th></tr>
                <tr>
                    <td title="''')
                _v = VFFSL(SL,"allt",True) # '$allt' on line 35, col 32
                if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 35, col 32.
                write('''" class="''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 35, col 46
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 35, col 46.
                write('''">''')
                _v = VFFSL(SL,"PYTHON_CPU",True) # '$PYTHON_CPU' on line 35, col 61
                if _v is not None: write(_filter(_v, rawExpr='$PYTHON_CPU')) # from line 35, col 61.
                write('''%</td>
                    <td class="Label">''')
                _v = VFFSL(SL,"ramt",True) # '$ramt' on line 36, col 39
                if _v is not None: write(_filter(_v, rawExpr='$ramt')) # from line 36, col 39.
                write('''</td>
                    <td title="''')
                _v = VFFSL(SL,"ont",True) # '$ont' on line 37, col 32
                if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 37, col 32.
                write('''" class="Label">''')
                _v = VFFSL(SL,"PYTHON_RAM",True) # '$PYTHON_RAM' on line 37, col 52
                if _v is not None: write(_filter(_v, rawExpr='$PYTHON_RAM')) # from line 37, col 52.
                write('''%</td>
                </tr>
                <tr><th colspan="3" rowspan="1">\xd1\xe5\xf0\xe2\xe5\xf0</th></tr>
''')
            else: # generated from line 40, col 9
                Class_Health = 'HealthGood'
                if VFFSL(SL,"PYTHON_THREADS",True)>VFFSL(SL,"PYTHON_ACTIVE_THREADS",True): # generated from line 42, col 13
                    Class_Health = 'HealthBad'
                write('''            <table>
            <tr><td rowspan="5" class="logo ''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 46, col 45
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 46, col 45.
                write('''"></td><th colspan="3" rowspan="1">\xd1\xe5\xf0\xe2\xe5\xf0</th></tr>
''')
            write('''            <tr>
                <td class="Left ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 49, col 33
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 49, col 33.
            write('''">''')
            _v = VFFSL(SL,"threadst",True) # '$threadst' on line 49, col 48
            if _v is not None: write(_filter(_v, rawExpr='$threadst')) # from line 49, col 48.
            write(''':</td>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 50, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 50, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"PYTHON_THREADS",True) # '$PYTHON_THREADS' on line 50, col 52
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_THREADS')) # from line 50, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"activet",True) # '$activet' on line 51, col 28
            if _v is not None: write(_filter(_v, rawExpr='$activet')) # from line 51, col 28.
            write('''" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 51, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 51, col 45.
            write(''' AlignRight">''')
            _v = VFFSL(SL,"PYTHON_ACTIVE_THREADS",True) # '$PYTHON_ACTIVE_THREADS' on line 51, col 71
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_ACTIVE_THREADS')) # from line 51, col 71.
            write('''</td>
            </tr>
            <tr>
                <td class="Left">''')
            _v = VFFSL(SL,"serverauserst",True) # '$serverauserst' on line 54, col 34
            if _v is not None: write(_filter(_v, rawExpr='$serverauserst')) # from line 54, col 34.
            write(''':</td>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 55, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 55, col 28.
            write('''" class="AlignRight">''')
            _v = VFFSL(SL,"PYTHON_COUNT_USERS",True) # '$PYTHON_COUNT_USERS' on line 55, col 54
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_COUNT_USERS')) # from line 55, col 54.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"activet",True) # '$activet' on line 56, col 28
            if _v is not None: write(_filter(_v, rawExpr='$activet')) # from line 56, col 28.
            write('''" class="AlignRight">''')
            _v = VFFSL(SL,"PYTHON_COUNT_ACTIVE_USERS",True) # '$PYTHON_COUNT_ACTIVE_USERS' on line 56, col 57
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_COUNT_ACTIVE_USERS')) # from line 56, col 57.
            write('''</td>
            </tr>
''')
            Class_Health = 'HealthGood'
            if VFFSL(SL,"PYTHON_ACTIVE_TRANS",True)>10: # generated from line 59, col 17
                Class_Health = 'HealthBad'
            write('''            <tr>
                <td class="Left ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 63, col 33
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 63, col 33.
            write('''">''')
            _v = VFFSL(SL,"transt",True) # '$transt' on line 63, col 48
            if _v is not None: write(_filter(_v, rawExpr='$transt')) # from line 63, col 48.
            write(''':</td>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 64, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 64, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"PYTHON_TRANS",True) # '$PYTHON_TRANS' on line 64, col 52
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_TRANS')) # from line 64, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"activet",True) # '$activet' on line 65, col 28
            if _v is not None: write(_filter(_v, rawExpr='$activet')) # from line 65, col 28.
            write('''" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 65, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 65, col 45.
            write(''' AlignRight">''')
            _v = VFFSL(SL,"PYTHON_ACTIVE_TRANS",True) # '$PYTHON_ACTIVE_TRANS' on line 65, col 71
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_ACTIVE_TRANS')) # from line 65, col 71.
            write('''</td>
            </tr>
            <tr>
                <td colspan="1" rowspan="1" class="Left">''')
            _v = VFFSL(SL,"servertimet",True) # '$servertimet' on line 68, col 58
            if _v is not None: write(_filter(_v, rawExpr='$servertimet')) # from line 68, col 58.
            write(''':</td>
                <td colspan="2" rowspan="1" class="Label">''')
            _v = VFFSL(SL,"PYTHON_SERVER_TIME",True) # '$PYTHON_SERVER_TIME' on line 69, col 59
            if _v is not None: write(_filter(_v, rawExpr='$PYTHON_SERVER_TIME')) # from line 69, col 59.
            write('''</td>
            </tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'SALE': # generated from line 74, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_SALE_TASKS_ON",True) > 0: # generated from line 76, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row SALE">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 81, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 81, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xce\xed\xeb\xe0\xe9\xed \xef\xf0\xee\xe4\xe0\xe6\xe8</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 83, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 83, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_SALE_TASKS",True) # '$CNT_SALE_TASKS' on line 83, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SALE_TASKS')) # from line 83, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 84, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 84, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_SALE_TASKS_OFF",True) # '$CNT_SALE_TASKS_OFF' on line 84, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SALE_TASKS_OFF')) # from line 84, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 85, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 85, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_SALE_TASKS_ERR",True) # '$CNT_SALE_TASKS_ERR' on line 85, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SALE_TASKS_ERR')) # from line 85, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 86, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 86, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_SALE_TASKS_ON",True) # '$CNT_SALE_TASKS_ON' on line 86, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SALE_TASKS_ON')) # from line 86, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 88, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 88, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 88, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 88, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_SALE_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_SALE_TASKS_OFF,$dateformat)' on line 88, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_SALE_TASKS_OFF,$dateformat)')) # from line 88, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'PACKET': # generated from line 92, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_PACKET_TASKS_ON",True) > 0: # generated from line 94, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row PACKET">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 99, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 99, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xc2\xfb\xe3\xf0\xf3\xe7\xea\xe0 \xef\xe0\xea\xe5\xf2\xee\xe2</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 101, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 101, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_PACKET_TASKS",True) # '$CNT_PACKET_TASKS' on line 101, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PACKET_TASKS')) # from line 101, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 102, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 102, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_PACKET_TASKS_OFF",True) # '$CNT_PACKET_TASKS_OFF' on line 102, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PACKET_TASKS_OFF')) # from line 102, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 103, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 103, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_PACKET_TASKS_ERR",True) # '$CNT_PACKET_TASKS_ERR' on line 103, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PACKET_TASKS_ERR')) # from line 103, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 104, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 104, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_PACKET_TASKS_ON",True) # '$CNT_PACKET_TASKS_ON' on line 104, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PACKET_TASKS_ON')) # from line 104, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 106, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 106, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 106, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 106, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_PACKET_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_PACKET_TASKS_OFF,$dateformat)' on line 106, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_PACKET_TASKS_OFF,$dateformat)')) # from line 106, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'AORDERSTAT': # generated from line 110, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_AORDERSTAT_TASKS_ON",True) > 0: # generated from line 112, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row AORDERSTAT">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 117, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 117, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xd1\xf2\xe0\xf2\xe8\xf1\xf2\xe8\xea\xe0 \xe0\xe2\xf2\xee\xe7\xe0\xea\xe0\xe7\xe0</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 119, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 119, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_AORDERSTAT_TASKS",True) # '$CNT_AORDERSTAT_TASKS' on line 119, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDERSTAT_TASKS')) # from line 119, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 120, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 120, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_AORDERSTAT_TASKS_OFF",True) # '$CNT_AORDERSTAT_TASKS_OFF' on line 120, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDERSTAT_TASKS_OFF')) # from line 120, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 121, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 121, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_AORDERSTAT_TASKS_ERR",True) # '$CNT_AORDERSTAT_TASKS_ERR' on line 121, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDERSTAT_TASKS_ERR')) # from line 121, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 122, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 122, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_AORDERSTAT_TASKS_ON",True) # '$CNT_AORDERSTAT_TASKS_ON' on line 122, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDERSTAT_TASKS_ON')) # from line 122, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 124, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 124, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 124, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 124, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_AORDERSTAT_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_AORDERSTAT_TASKS_OFF,$dateformat)' on line 124, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_AORDERSTAT_TASKS_OFF,$dateformat)')) # from line 124, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'AORDER': # generated from line 128, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_AORDER_TASKS_ON",True) > 0: # generated from line 130, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row AORDER">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 135, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 135, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xd0\xe0\xf1\xf7\xe5\xf2 \xe0\xe2\xf2\xee\xe7\xe0\xea\xe0\xe7\xe0</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 137, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 137, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_AORDER_TASKS",True) # '$CNT_AORDER_TASKS' on line 137, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDER_TASKS')) # from line 137, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 138, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 138, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_AORDER_TASKS_OFF",True) # '$CNT_AORDER_TASKS_OFF' on line 138, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDER_TASKS_OFF')) # from line 138, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 139, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 139, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_AORDER_TASKS_ERR",True) # '$CNT_AORDER_TASKS_ERR' on line 139, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDER_TASKS_ERR')) # from line 139, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 140, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 140, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_AORDER_TASKS_ON",True) # '$CNT_AORDER_TASKS_ON' on line 140, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_AORDER_TASKS_ON')) # from line 140, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 142, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 142, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 142, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 142, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_AORDER_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_AORDER_TASKS_OFF,$dateformat)' on line 142, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_AORDER_TASKS_OFF,$dateformat)')) # from line 142, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'RORDER': # generated from line 146, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_RORDER_TASKS_ON",True) > 0: # generated from line 148, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row RORDER">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 153, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 153, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xd0\xee\xf1\xef\xe8\xf1\xfc</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 155, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 155, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_RORDER_TASKS",True) # '$CNT_RORDER_TASKS' on line 155, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_RORDER_TASKS')) # from line 155, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 156, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 156, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_RORDER_TASKS_OFF",True) # '$CNT_RORDER_TASKS_OFF' on line 156, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_RORDER_TASKS_OFF')) # from line 156, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 157, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 157, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_RORDER_TASKS_ERR",True) # '$CNT_RORDER_TASKS_ERR' on line 157, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_RORDER_TASKS_ERR')) # from line 157, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 158, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 158, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_RORDER_TASKS_ON",True) # '$CNT_RORDER_TASKS_ON' on line 158, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_RORDER_TASKS_ON')) # from line 158, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 160, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 160, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 160, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 160, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_RORDER_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_RORDER_TASKS_OFF,$dateformat)' on line 160, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_RORDER_TASKS_OFF,$dateformat)')) # from line 160, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'PRICING': # generated from line 164, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_PRICING_TASKS_ON",True) > 0: # generated from line 166, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row PRICING">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 171, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 171, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xd6\xe5\xed\xee\xee\xe1\xf0\xe0\xe7\xee\xe2\xe0\xed\xe8\xe5</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 173, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 173, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_PRICING_TASKS",True) # '$CNT_PRICING_TASKS' on line 173, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PRICING_TASKS')) # from line 173, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 174, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 174, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_PRICING_TASKS_OFF",True) # '$CNT_PRICING_TASKS_OFF' on line 174, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PRICING_TASKS_OFF')) # from line 174, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 175, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 175, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_PRICING_TASKS_ERR",True) # '$CNT_PRICING_TASKS_ERR' on line 175, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PRICING_TASKS_ERR')) # from line 175, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 176, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 176, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_PRICING_TASKS_ON",True) # '$CNT_PRICING_TASKS_ON' on line 176, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_PRICING_TASKS_ON')) # from line 176, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 178, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 178, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 178, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 178, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_PRICING_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_PRICING_TASKS_OFF,$dateformat)' on line 178, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_PRICING_TASKS_OFF,$dateformat)')) # from line 178, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'WSETPRLIST': # generated from line 182, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_WSETPRLIST_TASKS_ON",True) > 0: # generated from line 184, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row WSETPRLIST">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 189, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 189, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xcf\xf0\xe0\xe9\xf1-\xeb\xe8\xf1\xf2\xfb</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 191, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 191, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_WSETPRLIST_TASKS",True) # '$CNT_WSETPRLIST_TASKS' on line 191, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_WSETPRLIST_TASKS')) # from line 191, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 192, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 192, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_WSETPRLIST_TASKS_OFF",True) # '$CNT_WSETPRLIST_TASKS_OFF' on line 192, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_WSETPRLIST_TASKS_OFF')) # from line 192, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 193, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 193, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_WSETPRLIST_TASKS_ERR",True) # '$CNT_WSETPRLIST_TASKS_ERR' on line 193, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_WSETPRLIST_TASKS_ERR')) # from line 193, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 194, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 194, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_WSETPRLIST_TASKS_ON",True) # '$CNT_WSETPRLIST_TASKS_ON' on line 194, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_WSETPRLIST_TASKS_ON')) # from line 194, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 196, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 196, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 196, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 196, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_WSETPRLIST_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_WSETPRLIST_TASKS_OFF,$dateformat)' on line 196, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_WSETPRLIST_TASKS_OFF,$dateformat)')) # from line 196, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'SHARE': # generated from line 200, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_SHARE_TASKS_ON",True) > 0: # generated from line 202, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row SHARE">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 207, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 207, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xc0\xea\xf6\xe8\xe8</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 209, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 209, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_SHARE_TASKS",True) # '$CNT_SHARE_TASKS' on line 209, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SHARE_TASKS')) # from line 209, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 210, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 210, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_SHARE_TASKS_OFF",True) # '$CNT_SHARE_TASKS_OFF' on line 210, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SHARE_TASKS_OFF')) # from line 210, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 211, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 211, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_SHARE_TASKS_ERR",True) # '$CNT_SHARE_TASKS_ERR' on line 211, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SHARE_TASKS_ERR')) # from line 211, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 212, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 212, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_SHARE_TASKS_ON",True) # '$CNT_SHARE_TASKS_ON' on line 212, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_SHARE_TASKS_ON')) # from line 212, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 214, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 214, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 214, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 214, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_SHARE_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_SHARE_TASKS_OFF,$dateformat)' on line 214, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_SHARE_TASKS_OFF,$dateformat)')) # from line 214, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'MAINSUPPLIERS': # generated from line 218, col 1
            Class_Health = 'HealthGood'
            if VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS_ON",True) > 0: # generated from line 220, col 5
                Class_Health = 'HealthBad'
            write('''    <div class="row MAINSUPPLIERS">
        <table>
            <tr><td rowspan="3" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 225, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 225, col 45.
            write('''"></td><th colspan="4" rowspan="1">\xce\xf1\xed\xee\xe2\xed\xee\xe9 \xef\xee\xf1\xf2\xe0\xe2\xf9\xe8\xea</th></tr>
            <tr>
                <td title="''')
            _v = VFFSL(SL,"allt",True) # '$allt' on line 227, col 28
            if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 227, col 28.
            write('''" class="AllTasks">''')
            _v = VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS",True) # '$CNT_MAINSUPPLIERS_TASKS' on line 227, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_MAINSUPPLIERS_TASKS')) # from line 227, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"offt",True) # '$offt' on line 228, col 28
            if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 228, col 28.
            write('''" class="OffTasks">''')
            _v = VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS_OFF",True) # '$CNT_MAINSUPPLIERS_TASKS_OFF' on line 228, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_MAINSUPPLIERS_TASKS_OFF')) # from line 228, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"errt",True) # '$errt' on line 229, col 28
            if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 229, col 28.
            write('''" class="ErrTasks">''')
            _v = VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS_ERR",True) # '$CNT_MAINSUPPLIERS_TASKS_ERR' on line 229, col 52
            if _v is not None: write(_filter(_v, rawExpr='$CNT_MAINSUPPLIERS_TASKS_ERR')) # from line 229, col 52.
            write('''</td>
                <td title="''')
            _v = VFFSL(SL,"ont",True) # '$ont' on line 230, col 28
            if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 230, col 28.
            write('''" class="OnTasks">''')
            _v = VFFSL(SL,"CNT_MAINSUPPLIERS_TASKS_ON",True) # '$CNT_MAINSUPPLIERS_TASKS_ON' on line 230, col 50
            if _v is not None: write(_filter(_v, rawExpr='$CNT_MAINSUPPLIERS_TASKS_ON')) # from line 230, col 50.
            write('''</td>
            </tr>
            <tr><td colspan="4" rowspan="1" class="''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 232, col 52
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 232, col 52.
            write('''" title="''')
            _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 232, col 74
            if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 232, col 74.
            write('''">''')
            _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"LD_MAINSUPPLIERS_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($LD_MAINSUPPLIERS_TASKS_OFF,$dateformat)' on line 232, col 86
            if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($LD_MAINSUPPLIERS_TASKS_OFF,$dateformat)')) # from line 232, col 86.
            write('''</td></tr>
        </table>
    </div>
''')
        if VFFSL(SL,"refresh_block",True) == 'ROBOTS': # generated from line 236, col 1
            write('''    <div class="row ROBOTS">
        <table> 
''')
            Class_Health = 'HealthGood'
            if VFFSL(SL,"health",True) > 0: # generated from line 240, col 13
                Class_Health = 'HealthBad'
            write('''            <tr><td rowspan="7" class="logo ''')
            _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 243, col 45
            if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 243, col 45.
            write('''"></td><th colspan="5" rowspan="1">\xd0\xee\xe1\xee\xf2\xfb \xef\xe5\xf0\xe5\xee\xf6\xe5\xed\xea\xe8</th></tr>
''')
            for item in VFFSL(SL,"datalist",True): # generated from line 244, col 15
                Class_Health = 'HealthGood'
                if VFFSL(SL,"item.CNT_ROBOT_TASKS_ON",True) > 0: # generated from line 246, col 19
                    Class_Health = 'HealthBad'
                write('''                  <tr>
                      <td class="Label ''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 250, col 40
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 250, col 40.
                write('''" title="IP \xf0\xee\xe1\xee\xf2\xe0" colspan="1" rowspan="2">''')
                _v = VFFSL(SL,"item.IP_ROBOT",True) # '$item.IP_ROBOT' on line 250, col 97
                if _v is not None: write(_filter(_v, rawExpr='$item.IP_ROBOT')) # from line 250, col 97.
                write('''</td>
                      <td title="''')
                _v = VFFSL(SL,"allt",True) # '$allt' on line 251, col 34
                if _v is not None: write(_filter(_v, rawExpr='$allt')) # from line 251, col 34.
                write('''" class="AllTasks">''')
                _v = VFFSL(SL,"item.CNT_ROBOT_TASKS",True) # '$item.CNT_ROBOT_TASKS' on line 251, col 58
                if _v is not None: write(_filter(_v, rawExpr='$item.CNT_ROBOT_TASKS')) # from line 251, col 58.
                write('''</td>
                      <td title="''')
                _v = VFFSL(SL,"offt",True) # '$offt' on line 252, col 34
                if _v is not None: write(_filter(_v, rawExpr='$offt')) # from line 252, col 34.
                write('''" class="OffTasks">''')
                _v = VFFSL(SL,"item.CNT_ROBOT_TASKS_OFF",True) # '$item.CNT_ROBOT_TASKS_OFF' on line 252, col 58
                if _v is not None: write(_filter(_v, rawExpr='$item.CNT_ROBOT_TASKS_OFF')) # from line 252, col 58.
                write('''</td>
                      <td title="''')
                _v = VFFSL(SL,"errt",True) # '$errt' on line 253, col 34
                if _v is not None: write(_filter(_v, rawExpr='$errt')) # from line 253, col 34.
                write('''" class="ErrTasks">''')
                _v = VFFSL(SL,"item.CNT_ROBOT_TASKS_ERR",True) # '$item.CNT_ROBOT_TASKS_ERR' on line 253, col 58
                if _v is not None: write(_filter(_v, rawExpr='$item.CNT_ROBOT_TASKS_ERR')) # from line 253, col 58.
                write('''</td>
                      <td title="''')
                _v = VFFSL(SL,"ont",True) # '$ont' on line 254, col 34
                if _v is not None: write(_filter(_v, rawExpr='$ont')) # from line 254, col 34.
                write('''" class="OnTasks">''')
                _v = VFFSL(SL,"item.CNT_ROBOT_TASKS_ON",True) # '$item.CNT_ROBOT_TASKS_ON' on line 254, col 56
                if _v is not None: write(_filter(_v, rawExpr='$item.CNT_ROBOT_TASKS_ON')) # from line 254, col 56.
                write('''</td>
                  </tr>
                  <tr><td class="''')
                _v = VFFSL(SL,"Class_Health",True) # '$Class_Health' on line 256, col 34
                if _v is not None: write(_filter(_v, rawExpr='$Class_Health')) # from line 256, col 34.
                write('''" title="''')
                _v = VFFSL(SL,"lastdatet",True) # '$lastdatet' on line 256, col 56
                if _v is not None: write(_filter(_v, rawExpr='$lastdatet')) # from line 256, col 56.
                write('''" colspan="4" rowspan="1">''')
                _v = VFFSL(SL,"formatMxDateTime",False)(VFFSL(SL,"item.LD_ROBOT_TASKS_OFF",True),VFFSL(SL,"dateformat",True)) # '$formatMxDateTime($item.LD_ROBOT_TASKS_OFF,$dateformat)' on line 256, col 92
                if _v is not None: write(_filter(_v, rawExpr='$formatMxDateTime($item.LD_ROBOT_TASKS_OFF,$dateformat)')) # from line 256, col 92.
                write('''</td></tr>
''')
            write('''        </table>
    </div>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_health_blocks_mobile= 'respond'

## END CLASS DEFINITION

if not hasattr(health_blocks_mobile, '_initCheetahAttributes'):
    templateAPIClass = getattr(health_blocks_mobile, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(health_blocks_mobile)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=health_blocks_mobile()).run()


