execute block
as
begin
    INSERT INTO DOCTYPE (DOCTID, NAME, DEBET, CREDIT, CHECKNUMBER, HASTRANSACTS, HASWARES, HIGHER, CALCSUMFROM, MULTIPLE, MAXSUM, CHECKWARESSET, FIRSTSTATUS, ENUMTID, VIEWDAYS, CHECKNUMPERIOD, CODE, PRICEID, AFTERINSACTION, AUTOTRANSACT, MULSCALEID, CARGOMETHOD, WARESSTATUSES, WARESTYPES, CHECKAMOUNTSUMSIGN, ENABLED, NUM, SESSIONID, MULMETHOD, REASON, MINSUM, CHECKSUMSIGN, CHECKAMOUNTSIGN, DEFSUBTYPE, SUBTYPEREQUIRED, K_PRINTNAME, MINAMOUNT, MAXAMOUNT, ENUMDOCTOBJID, MAXCARGOCOUNT, K_PRINTTMPL, DOCMANAGEREDITDISABLE, EXPORTTAGNAME, DOCSUBTYPEIFNULL, WSETID, APPROVEDSTATUS, CANCREATE, EXTERNALCODE)
    VALUES (31, 'Приход резерва',  NULL, NULL, '0', '0', '1', NULL, '2', NULL, NULL, '0', '0', NULL, 3, NULL, 'FUNDINCOME', NULL, NULL, '0', NULL, 'T', NULL, NULL, '0', '1', 10, NULL, NULL, NULL, 0, '2', '2', NULL, '0', 'Накладная на приход', 0, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL);
    INSERT INTO DOCTYPEOBJ (DOCTID, NUMOBJ, OBJCATID, ISOWNER, OBJID, CANCHOICE, REQUIRED, ISCOMPANY, ISMAN, ISDEPART, WARESRESTCHANGE, WARESCIRCTYPE, CHECKWARESREST, MONEYRESTCHANGE, MONEYCIRCTYPE, CHECKMONEYREST, CAPTION, SESSIONID, LASTDATE, MONEYNUMOBJ2, RESTCHECK, RESTAMOUNTCHECK, OBJFILTID, OBJSTATUSES, WARESLOTTYPE, NUM, WARESRESTTYPE, MONEYRESTTYPE, ISOBJZONE)
    VALUES (31, '2', NULL, '0', NULL, '1', '1', '0', '0', '1', '2', '1', '1', '1', '1', '1', 'Склад', 1, '13-JUN-2014 15:06:00', NULL, '2', '0', NULL, NULL, NULL, 0, '0', '0', 's');
    INSERT INTO DOCTYPEOBJ (DOCTID, NUMOBJ, OBJCATID, ISOWNER, OBJID, CANCHOICE, REQUIRED, ISCOMPANY, ISMAN, ISDEPART, WARESRESTCHANGE, WARESCIRCTYPE, CHECKWARESREST, MONEYRESTCHANGE, MONEYCIRCTYPE, CHECKMONEYREST, CAPTION, SESSIONID, LASTDATE, MONEYNUMOBJ2, RESTCHECK, RESTAMOUNTCHECK, OBJFILTID, OBJSTATUSES, WARESLOTTYPE, NUM, WARESRESTTYPE, MONEYRESTTYPE, ISOBJZONE)
    VALUES (31, '0', NULL, '0', NULL, '1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1', 'Производитель', 1, '13-JUN-2014 15:06:17', NULL, '2', '0', NULL, NULL, NULL, 2, '0', '0', NULL);
    
    UPDATE doctypestatus dts
       set dts.upcodes = NULL, dts.updefcode = NULL, dts.downcodes = NULL, dts.downdefcode = NULL
     where dts.doctid = 31 and dts.code = '0';
    delete from doctypestatus dts
     where dts.doctid = 31 and dts.code <> '0';


    INSERT INTO DOCTYPESTATUS (DOCTID, CODE, UPCODES, DOWNCODES, SESSIONID, LASTDATE, WARESCHANGE, MONEYCHANGE, MINSUM, MAXSUM, UPDEFCODE, DOWNDEFCODE, DOCMANAGEREDITDISABLE, ACTIONSTATUS, CHECKTLAMOUNT, NUMORDER, FLAGS)
    VALUES (31, 'c', NULL, NULL, NULL, '18-AUG-2016 02:44:03', '0', '0', NULL, NULL, NULL, NULL, '1', 'N', NULL, NULL, NULL);
    UPDATE doctypestatus dts
       set dts.upcodes = 'c', dts.docmanagereditdisable = '1'
     where dts.doctid = 31 and dts.code = '0';

    INSERT INTO DOCTYPESTATUS (DOCTID, CODE, UPCODES, DOWNCODES, SESSIONID, LASTDATE, WARESCHANGE, MONEYCHANGE, MINSUM, MAXSUM, UPDEFCODE, DOWNDEFCODE, DOCMANAGEREDITDISABLE, ACTIONSTATUS, CHECKTLAMOUNT, NUMORDER, FLAGS)
    VALUES (31, 'w', NULL, NULL, NULL, '18-AUG-2016 02:44:03', '0', '0', NULL, NULL, NULL, NULL, '1', 'N', NULL, NULL, NULL);
    UPDATE doctypestatus dts
       set dts.upcodes = 'w'
     where dts.doctid = 31 and dts.code = 'c';

    INSERT INTO DOCTYPESTATUS (DOCTID, CODE, UPCODES, DOWNCODES, SESSIONID, LASTDATE, WARESCHANGE, MONEYCHANGE, MINSUM, MAXSUM, UPDEFCODE, DOWNDEFCODE, DOCMANAGEREDITDISABLE, ACTIONSTATUS, CHECKTLAMOUNT, NUMORDER, FLAGS)
    VALUES (31, 'e', NULL, NULL, NULL, '18-AUG-2016 02:44:03', '0', '0', NULL, NULL, NULL, NULL, '1', 'N', NULL, NULL, NULL);
end
