execute block
as
declare variable dtid type of column DOCTYPE.doctid = 38;
begin
    INSERT INTO DOCTYPE (DOCTID, NAME, DEBET, CREDIT, CHECKNUMBER, HASTRANSACTS, HASWARES, HIGHER, CALCSUMFROM, MULTIPLE, MAXSUM, CHECKWARESSET, FIRSTSTATUS, ENUMTID, VIEWDAYS, CHECKNUMPERIOD, CODE, PRICEID, AFTERINSACTION, AUTOTRANSACT, MULSCALEID, CARGOMETHOD, WARESSTATUSES, WARESTYPES, CHECKAMOUNTSUMSIGN, ENABLED, NUM, SESSIONID, MULMETHOD, REASON, MINSUM, CHECKSUMSIGN, CHECKAMOUNTSIGN, DEFSUBTYPE, SUBTYPEREQUIRED, K_PRINTNAME, MINAMOUNT, MAXAMOUNT, ENUMDOCTOBJID, MAXCARGOCOUNT, K_PRINTTMPL, DOCMANAGEREDITDISABLE, EXPORTTAGNAME, DOCSUBTYPEIFNULL, WSETID, APPROVEDSTATUS, CANCREATE, EXTERNALCODE)
    VALUES (:dtid, 'Перемещение резерва',  NULL, NULL, '0', '0', '1', NULL, '2', NULL, NULL, '0', '0', NULL, 3, NULL, 'FUNDMOVING', NULL, NULL, '0', NULL, 'T', NULL, NULL, '0', '1', 10, NULL, NULL, NULL, 0, '2', '2', NULL, '0', NULL, 0, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL);

    INSERT INTO DOCTYPEOBJ (DOCTID, NUMOBJ, OBJCATID, ISOWNER, OBJID, CANCHOICE, REQUIRED, ISCOMPANY, ISMAN, ISDEPART, WARESRESTCHANGE, WARESCIRCTYPE, CHECKWARESREST, MONEYRESTCHANGE, MONEYCIRCTYPE, CHECKMONEYREST, CAPTION, SESSIONID, LASTDATE, MONEYNUMOBJ2, RESTCHECK, RESTAMOUNTCHECK, OBJFILTID, OBJSTATUSES, WARESLOTTYPE, NUM, WARESRESTTYPE, MONEYRESTTYPE, ISOBJZONE)
    VALUES (:dtid, '2', NULL, '0', NULL, '1', '1', '0', '0', '1', '2', '1', '1', '1', '1', '1', 'От кого', 1, '13-JUN-2014 15:06:00', NULL, '2', '0', NULL, NULL, NULL, 0, '0', '0', NULL);

    INSERT INTO DOCTYPEOBJ (DOCTID, NUMOBJ, OBJCATID, ISOWNER, OBJID, CANCHOICE, REQUIRED, ISCOMPANY, ISMAN, ISDEPART, WARESRESTCHANGE, WARESCIRCTYPE, CHECKWARESREST, MONEYRESTCHANGE, MONEYCIRCTYPE, CHECKMONEYREST, CAPTION, SESSIONID, LASTDATE, MONEYNUMOBJ2, RESTCHECK, RESTAMOUNTCHECK, OBJFILTID, OBJSTATUSES, WARESLOTTYPE, NUM, WARESRESTTYPE, MONEYRESTTYPE, ISOBJZONE)
    VALUES (:dtid, '1', NULL, '0', NULL, '1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1', 'Клиент', NULL, '4-JUN-2014 15:10:30', NULL, '2', '0', NULL, NULL, NULL, 1, '0', '0', NULL);

    INSERT INTO DOCTYPEOBJ (DOCTID, NUMOBJ, OBJCATID, ISOWNER, OBJID, CANCHOICE, REQUIRED, ISCOMPANY, ISMAN, ISDEPART, WARESRESTCHANGE, WARESCIRCTYPE, CHECKWARESREST, MONEYRESTCHANGE, MONEYCIRCTYPE, CHECKMONEYREST, CAPTION, SESSIONID, LASTDATE, MONEYNUMOBJ2, RESTCHECK, RESTAMOUNTCHECK, OBJFILTID, OBJSTATUSES, WARESLOTTYPE, NUM, WARESRESTTYPE, MONEYRESTTYPE, ISOBJZONE)
    VALUES (:dtid, '0', NULL, '0', NULL, '1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1', 'Кому', 1, '13-JUN-2014 15:06:17', NULL, '2', '0', NULL, NULL, NULL, 2, '0', '0', NULL);
    
    UPDATE doctypestatus dts
       set dts.wareschange = '0', dts.moneychange = '0'
     where dts.doctid = :dtid;
end

