
INSERT INTO DOCTYPEOBJ (DOCTID, NUMOBJ, OBJCATID, ISOWNER, OBJID, CANCHOICE, REQUIRED, ISCOMPANY, ISMAN, ISDEPART, WARESRESTCHANGE, WARESCIRCTYPE, CHECKWARESREST, MONEYRESTCHANGE, MONEYCIRCTYPE, CHECKMONEYREST, CAPTION, SESSIONID, LASTDATE, MONEYNUMOBJ2, RESTCHECK, RESTAMOUNTCHECK, OBJFILTID, OBJSTATUSES, WARESLOTTYPE, NUM, WARESRESTTYPE, MONEYRESTTYPE, ISOBJZONE)
VALUES (2, '1', NULL, '0', NULL, '1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1', 'Объект резерва', NULL, '24-AUG-2016 14:29:07', NULL, '2', '0', NULL, NULL, NULL, 1, '0', '0', NULL);
