delete from R_REPORT;

INSERT INTO R_REPORT (REPORTID, NAME, REPTYPE, ISLOCAL, FILENAME, PARAMS, COPIES, PRIORITY, ACTIONSPARAMS, HIGHER, PROTOTYPE, SESSIONID, LASTDATE, GROUPINDEX, QUESERVERID, MODULEID) VALUES (2, 'Шаблон этикетки готовой продукции', '0', '1', 'FinishGoodsPalletU3S.rbs', NULL, 1, NULL, NULL, NULL, NULL, 1, '12-NOV-2016 23:42:07', NULL, NULL, 10);
INSERT INTO R_REPORT (REPORTID, NAME, REPTYPE, ISLOCAL, FILENAME, PARAMS, COPIES, PRIORITY, ACTIONSPARAMS, HIGHER, PROTOTYPE, SESSIONID, LASTDATE, GROUPINDEX, QUESERVERID, MODULEID) VALUES (8, 'Шаблон этикетки на приемку возврата', '0', '1', 'ComeReturnPalletU3S.rbs', NULL, 1, NULL, NULL, NULL, NULL, 1, '7-NOV-2016 23:37:56', NULL, NULL, 10);
INSERT INTO R_REPORT (REPORTID, NAME, REPTYPE, ISLOCAL, FILENAME, PARAMS, COPIES, PRIORITY, ACTIONSPARAMS, HIGHER, PROTOTYPE, SESSIONID, LASTDATE, GROUPINDEX, QUESERVERID, MODULEID) VALUES (9, 'Шаблон этикетки приемки', '0', '1', 'IncomePalletU3S.rbs', NULL, 1, NULL, NULL, NULL, NULL, 1, '12-NOV-2016 23:40:44', NULL, NULL, 10);


UPDATE PALLET_TYPE
SET CODE = 'I',
    NAME = 'Приемки',
    OLDPALLETTYPE = '0',
    PREFIX = 'I',
    PROCWARESCHK = NULL,
    CANMOVE = '1',
    PROCREFILLCHK = '1',
    WARESID_PALLET = NULL,
    MINGENID = 1,
    MAXGENID = 99999,
    SERIES = 1,
    PREFIXNUM = 'I',
    PALNUMLENGTH = 5
WHERE (ID = 1);


