

CREATE GLOBAL TEMPORARY TABLE WH_TMP_RESERVEDOC_CHANGES (
    DOCID        R_ID64 /* R_ID64 = DOUBLE PRECISION */,
    WARESID      R_ID NOT NULL /* R_ID = INTEGER */,
    PRODUCTDATE  R_DATE NOT NULL /* R_DATE = DATE */,
    AMOUNT       R_DOUBLE /* R_DOUBLE = DOUBLE PRECISION */,
    OBJID        R_ID NOT NULL /* R_ID = INTEGER */,
    RDOCID       R_ID64 NOT NULL /* R_DOUBLE = DOUBLE PRECISION */
) ON COMMIT DELETE ROWS;


